name: Publish release

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - name: .NET setup
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json
      - name: Pack
        run: dotnet pack -o . -c Release /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="${{ github.event.release.body }}"
      - name: Push to Nuget
        run: dotnet nuget push *.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
